### ISSUE TITLE
Lose state if accusing incorrectly

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#21]

**Comment by AmmonHepworth** [comment]
If accusing fails:

You may make no further moves in the game.

You remain as a player to contradict Suggestions made by other players.

If your token is blocking a door, move it into Room so that other players may enter.

Your opponents may continue to move your token into the various Rooms where they make Suggestions.

**Comment by AmmonHepworth** [comment]
Also includes the win state. Just a message with the name of the winner and ending the game after a GUI notification of the winner

**Comment by carsonlloyd** [comment]
Skeleton of this is done. Failed accusation should be implemented, just need to add gui window on clients when they receive "game_win_accusation" message. Info is already passed in.
