### ISSUE TITLE
Weapons exist

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#9]

**Comment by AmmonHepworth** [comment]
Weapons should be implemented. It is not strictly necessary to have them show on the game map but they must be functional and randomly assigned

**Comment by rwalker675** [comment]
Assigned to Robert.

**Comment by rwalker675** [comment]
Assign to Robert.  
Can't be in hallways.
Move weapon to room. Check this.
Weapons enumeration.
Similar to RoomType.  This would be a WeaponType.
Class that is an enumeration.
Rooms will know what weapons are in the room.

**Comment by carsonlloyd** [comment]
Is this done?

**Comment by AmmonHepworth** [comment]
There is a weapon enumeration and it gets passed through messages. The only way a weapon moves is through suggest/accuse and so I think the only part missing is actually having the host initialize weapons into rooms. I suppose that doesnt really matter though since having weapons in rooms is purely cosmetic for both host and client

**Comment by carsonlloyd** [comment]
Initialized weapons to room in my branch for other functionality.
